### ISSUE TITLE
Is it possible to share the trained weights? Thanks

### ISSUE THREAD

**Issue by junyongyou** [woshidandan/TANet#10]
Dear authors, is it possible to publish or share the model weights trained on AVA or TAD66K dataset? I want to use the model in my work, but don't really want to retrain the model. Many thanks.

**Comment by junyongyou** [comment]
> Thanks for following our work. The weight of the model is in the folder of the code, SRCC_758_LCC_765.pth for AVA dataset, SRCC_513_LCC_531_MSE_016.pth for TAD66K dataset.

Ok, great, sorry I overlooked that. Thank you.

**Comment by xiewende** [comment]
Can we use this weight（SRCC_758_LCC_765.pth） to infer the accuracy of 0.94 provided in the paper?
