### ISSUE TITLE
How to get a pretrained backbone?

### ISSUE THREAD

**Issue by ZachL1** [woshidandan/TANet#14]
Can you share the download links for these two pretrained models:
https://github.com/woshidandan/TANet/blob/848a8621d0a9258cc75aa919c8427c57869f8257/code/AVA/train_nni.py#L144

https://github.com/woshidandan/TANet/blob/848a8621d0a9258cc75aa919c8427c57869f8257/code/AVA/train_nni.py#L157

**Comment by woshidandan** [comment]
model_file = './resnet18_places365.pth.tar'  in here:
![image](https://user-images.githubusercontent.com/15050507/236766238-09351c4f-dce2-4e95-ab6b-fe47075fac4d.png)

/mobilenetv2.pth.tar is here:
https://drive.google.com/file/d/1NfwKpU_b0au4NiWXH9w7nagoTJdMJE7R/view?usp=sharing

**Comment by ZachL1** [comment]
Thanks a lot!
