### ISSUE TITLE
载入预训练好的权重的推理结果

### ISSUE THREAD

**Issue by Zdxfgre** [woshidandan/TANet#19]
直接载入预训练好的权重在AVA和TAD66K上推理，指标似乎并不能达到模型上所写的，想问问原因是什么？
如AVA上直接载入权重的结果为lcc：0.764 srcc：0.755，TAD上为lcc：0.526 srcc：0.507

**Comment by xiewende** [comment]
我也是，请问你解决了这个问题吗？
