### ISSUE TITLE
数据集失效

### ISSUE THREAD

**Issue by wenwenaixuexi** [woshidandan/TANet#2]
你好，请问可以重新分享一下数据集链接吗~~失效啦

**Comment by woshidandan** [comment]
你好，链接已更新：https://drive.google.com/drive/folders/1b2D9LeeG5XZzhEa8ldnIZjGh0IHadHhU?usp=sharing
之前是因为会议有匿名的需求，我们用的是另一个匿名的网盘账号上传的，组里有同学不小心动了那个账号，现在已重新上传，试试吧！
祝好！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月7日(星期四) 上午9:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [woshidandan/TANet] 数据集失效 (Issue #2)





 
你好，请问可以重新分享一下数据集链接吗~~失效啦

**Comment by wenwenaixuexi** [comment]
谢谢你！
